scalar JSON

type Mutation {
    createEntityType(input: CreateEntityTypeInput!): EntityType!
    createBundle(input: CreateBundleInput!): Bundle!
    addFieldToBundle(input: AddFieldInput!): FieldDefinition!
}

input CreateEntityTypeInput {
    name: String!
    description: String
}

input CreateBundleInput {
    entityTypeID: ID!
    name: String!          # machine name
    label: String!         # human-readable
    fields: [FieldInput!]! # initial fields
}

input FieldInput {
    name: String!
    type: String!          # "text", "int", "reference", etc.
    required: Boolean!
    settings: JSON
}

input AddFieldInput {
    bundleID: ID!
    name: String!
    type: String!
    required: Boolean!
    settings: JSON
}

type EntityType {
    id: ID!
    name: String!
    description: String
}

type Bundle {
    id: ID!
    name: String!
    label: String!
    entityTypeID: ID!
    tableName: String!
}

type FieldDefinition {
    id: ID!
    bundleID: ID!
    name: String!
    type: String!
    required: Boolean!
    settings: JSON
}